### ISSUE TITLE
InputSelect changes auto-sizing width when selection drawer is opened

### ISSUE THREAD

**Issue by zackchengyk** [LifeSG/react-design-system#469] opened 2024-05-08 03:21 UTC
**Component**

`InputSelect`

**Describe the bug**

When using the `InputSelect` component in any context where its width is not fixed, and it's competing with other elements for horizontal space (e.g. in a `DataTable`, or with several siblings inside a `display: flex` parent), opening/closing the selection drawer changes the width of the component.

**To Reproduce**

Described above. Here are some minimal reproductions:

[in-flex.txt](https://github.com/LifeSG/react-design-system/files/15243403/in-flex.txt)

[in-table.txt](https://github.com/LifeSG/react-design-system/files/15243404/in-table.txt)

**Screen Recordings**

https://github.com/LifeSG/react-design-system/assets/61947377/8ed4b35f-90d7-4606-a67a-5b57a0e94e70

https://github.com/LifeSG/react-design-system/assets/61947377/46785023-545f-467e-ba07-633134c1a06a

**Comment by qroll** [comment] 2024-10-04 03:24
closing as I'm not able to reproduce this issue after the `InputSelect` rework done for https://github.com/LifeSG/react-design-system/issues/443

the other dropdown-based inputs likely exhibit the same behaviour but they will be updated incrementally

**Closed by qroll** 2024-10-04 03:24 UTC
Labels: bug
